### PR TITLE
Scale issues fix

### PR DESCRIPTION
**Pull request by thakurajayL**
1. Adding lock around calculate MAC
2. Changing pool size from 8k to 16k
3. Removal/modification  of some logs.

### CODE REVIEW

**Review by badhrinathpa — APPROVED** [review]
+1

**Comment by yoooou** [comment]
retest this please

**Comment by thakurajayL** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
