### PR TITLE
Default State for Attach Procedure

### PR DESCRIPTION
**Pull request by clstefi**
This activity contains the below changes:

1. Added a default state for attach procedure. Events added to this state will be automatically updated to the eventToAction map maintained by other states of the attach procedure.
2. Added a sample handling for s1 release collision during attach to demonstrate the above change.
3. Created one file per procedure states, moved all the state definitions/implementations to the per procedure file.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by sindack** [comment]
ok to test

**Review by thakurajayL — APPROVED** [review]

**Review by thakurajayL — APPROVED** [review]

**Pull request merged**
