### PR TITLE
Logs

### PR DESCRIPTION
**Pull request by thakurajayL**
Log cleanup
        Logs should not be dumped to file if its container based deployment
        logs should not cause fopen/fclose for every log
        Single file should not be used for all container logs

### CODE REVIEW

**Comment by thakurajayL** [comment]
@hariharanb77 @asreek  Can you please review ?

**Comment by asreek** [comment]
> @hariharanb77 @asreek Can you please review ?

No comments from my side.

**Comment by hariharanb77** [comment]
@thakurajayL , @pingping-lin ,
There seem to be a license check failure in this request. Can you check and confirm?

**Comment by thakurajayL** [comment]
retest this please

**Comment by thakurajayL** [comment]
@badhrinathpa @hariharanb77  Can you please merge

**Pull request merged**
