### PR TITLE
s10 code review

### PR DESCRIPTION
**Pull request by sauravpkr**
Kindly review this code for s10 with respect to NAS(MME-APP). We will soon submitting the s10 code with respect to GTP. 

Note:- Only positive scenarios are considered as of now. We will be adding the negative scenarios as well once this code tests successfully.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by hesam1992** [comment]
Hi @sauravpkr do you have any pcap of S10 commiunication between MMEs?

**Comment by sauravpkr** [comment]
Earlier i had but i dont have right now.


Regards,
Saurav

**Pull request closed without merging**
