### PR TITLE
Shorten License Header

### PR DESCRIPTION
**Pull request by clstefi**
This activity includes:

1.License header Updates
2. Prop from openmme w.r.t paging encoding

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by sindack** [comment]
ok to test

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
