### PR TITLE
Fix compilation on Ubuntu 18.04 and 20.04

### PR DESCRIPTION
**Pull request by btsimon97**
The current install_builddeps.sh script doesn't work on Ubuntu 20.04 due to some changes in package names on Ubuntu 20.04 and other differences.

These changes modify the install_builddeps.sh script to load the build dependencies for Nucleus on Ubuntu 20.04 as a prelude to being able to build Nucleus on that platform.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by btsimon97** [comment]
Hi, my employer is currently in the process of signing and submitting an institutional CLA as work was done under employment with them. In the meantime, I have added two additional commits to this PR which resolve issues preventing compilation of nucleus on Ubuntu 18.04 and 20.04.

**Pull request closed without merging**
