### PR TITLE
Add CI config files

### PR DESCRIPTION
**Pull request by yoooou**

### CODE REVIEW

**Comment by yoooou** [comment]
works with https://github.com/omec-project/omec-project-ci/pull/70

**Comment by thakurajayL** [comment]
Please dont merge any change in Nucleus/Master... Else @badhrinathpa  need to do git pull again.. He has massive difficulty in getting this merge done. We are avoiding all the merges for now.

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
