### PR TITLE
Concurrent Procedure Support

### PR DESCRIPTION
**Pull request by asreek**
This activity contains the following changes:
1. Adds support for concurrent procedures in the state machine framework.
2. Script optimizations.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by asreek** [comment]
Abandoning this PR. Changes were merged to 
https://github.com/omec-project/Nucleus/pull/83

**Pull request closed without merging**
