### PR TITLE
Change Key->cbIndex Map to Unordered Map

### PR DESCRIPTION
**Pull request by clstefi**
This activity includes the following script changes:

1. Changed the key->cbIdx map maintained by the DataGroupManager to unordered_map.
2. Supported API to return the map size.

### CODE REVIEW

**Comment by thakurajayL** [comment]
retest this please

**Review by thakurajayL — APPROVED** [review]

**Review by badhrinathpa — APPROVED** [review]
+1

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Pull request merged**
