### PR TITLE
Used Ans1 library to encode Attach ICSR

### PR DESCRIPTION
**Pull request by vthiruveedula**

### CODE REVIEW

**Comment by vthiruveedula** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Review by badhrinathpa — APPROVED** [review]
+1

**Pull request merged**
