### PR TITLE
Memory leak in s1ap container & mme-app container

### PR DESCRIPTION
**Pull request by thakurajayL**
Memory leak in s1ap container & mme-app container

### CODE REVIEW

**Comment by yoooou** [comment]
retest this please

**Review by badhrinathpa — APPROVED** [review]
+1

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by thakurajayL** [comment]
retest this please

**Comment by omecproject** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Pull request merged**
