### PR TITLE
license header updates

### PR DESCRIPTION
**Pull request by asreek**
This update contains:
1. License header updates
2. Prop from openmme branch wr.t paging encoding.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by asreek** [comment]
Abandoning.

**Pull request closed without merging**
